In [2]:
import numpy as np
#QR with Gram-Schmidt orthogonalisation
# for square matrices (n, n)
n = int(input()) #any integer input
v=[]
for _ in range(n):
  v_ = [int(i) for i in input().split()]
  #give columns of matrix as input with spaces
  v.append(v_)
w = [v[0]]
for j in range(1, n):
  s = 0
  for k in range(j):
    s += np.dot((np.dot(v[j], w[k])/np.linalg.norm(w[k])**2), w[k])
  w.append(list(v[j] - s))
# w = orthogonal set of vectors
q = []
for m in range(n):
  q.append(w[m]/np.linalg.norm(w[m])) #columns of Q
# dividing the vectors by their norm to make it orthogonal
print("Orthogonal matrix Q =\n", np.array(q).T) 
# R = Q transpose multiplied by A
print("Upper-triangular matrix R = \n", np.matmul(np.array(q), np.array(v).T))

4
3 4 5
1 8 2
7 8 9
-3 -2 1
Orthogonal matrix Q =
 [[ 0.42426407 -0.31843918  0.84770071  0.76626103]
 [ 0.56568542  0.82419551  0.02649065  0.28734789]
 [ 0.70710678 -0.46829291 -0.52981294  0.57469577]]
Upper-triangular matrix R = 
 [[ 7.07106781e+00  6.36396103e+00  1.38592929e+01 -1.69705627e+00]
 [ 3.88578059e-16  5.33853913e+00  1.49853730e-01 -1.16136641e+00]
 [ 9.99200722e-15  5.77315973e-15  1.37751365e+00 -3.12589636e+00]
 [ 6.32165348e+00  4.21443565e+00  1.28348722e+01 -2.29878308e+00]]
