In [4]:
import numpy as np
import math
A = []
# insert number of rows and columns respectively such that m >= n
m, n = [int(_) for _ in input().split()]
for _ in range(m):
  a1 = [int(__) for __ in input().split()] #insert row wise elements with space
  A.append(a1)
A = np.array(A)
Q = np.identity(m)
for i in range(n):
  for j in range(m-1,i,-1):
    if A[j][i] == 0:
      c = 1
      s = 0
    elif abs(A[j-1][i]) > abs(A[j][i]):
      t = A[j][i]/A[j-1][i]
      c = 1/math.sqrt(1+t**2)
      s = c*t
    elif abs(A[j-1][i]) < abs(A[j][i]):
      t = A[j-1][i]/A[j][i]
      s = 1/math.sqrt(1+t**2)
      c = s*t
    g = np.identity(m)
    g[j-1][j-1], g[j][j] = c, c
    g[j-1][j], g[j][j-1] = s, -s
    A = np.matmul(g, A)
    Q = np.matmul(Q, g.T)
print("The upper triangular matrix R is \n", A)
print("The orthogonal matrix Q \n",Q)

4 3
3 4 5
-6 -4 2
1 8 2
7 8 9
The upper triangular matrix R is 
 [[ 9.74679434e+00  1.02597835e+01  6.97665279e+00]
 [-5.00093590e-16 -7.39843511e+00 -3.84149515e+00]
 [ 7.93908373e-16  7.76692899e-17  7.11120459e+00]
 [ 1.61193976e-16  6.03323625e-17 -1.44184284e-16]]
The orthogonal matrix Q 
 [[ 0.30779351 -0.11382208  0.339659   -0.88144169]
 [-0.61558701 -0.31301072  0.71609636  0.1014048 ]
 [ 0.10259784 -0.93903215 -0.3266784   0.03120148]
 [ 0.71818485 -0.08536656  0.51489708  0.46022177]]
