In [3]:
import numpy as np
A = []
# insert number of rows and columns respectively such that m >= n
m, n = [int(_) for _ in input().split()]
for _ in range(m):
  a1 = [int(__) for __ in input().split()] #insert row wise elements with space
  A.append(a1)
A = np.array(A)
sign = lambda x: 1 if x >= 0 else -1
Q1 = np.identity(m)
for i in range(n):
  u = (A[i:, i:][:,0]/np.linalg.norm(A[i:, i:][:,0])).reshape(m-i,1)
  v = (-sign(A[i:, i:][0][0])*np.array(([1] + [0]*(m-i-1)))).reshape(m-i, 1)
  w = (u-v)/np.linalg.norm(u-v)
  w = w.reshape(m-i, 1)
  H = np.identity(m-i)-2*np.matmul(w, w.T)
  Q = np.identity(m)
  for j in range(i,m):
    for k in range(i, m):
      Q[j][k] = H[j-i][k-i]
  A = np.matmul(Q, A)
  Q1 = np.matmul(Q1, Q)
print("The upper triangular matrix R is", A)
print("The orthogonal matrix Q",Q1)
print(np.matmul(Q1,A))

4 3
3 4 5
-6 -4 2
1 8 2
7 8 9
The upper triangular matrix R is [[-9.74679434e+00 -1.02597835e+01 -6.97665279e+00]
 [-1.72097312e-16 -7.39843511e+00 -3.84149515e+00]
 [ 2.71861402e-16 -1.14914577e-15  7.11120459e+00]
 [ 6.06740584e-16  3.77436465e-16 -1.66592209e-16]]
The orthogonal matrix Q [[-0.30779351 -0.11382208  0.339659   -0.88144169]
 [ 0.61558701 -0.31301072  0.71609636  0.1014048 ]
 [-0.10259784 -0.93903215 -0.3266784   0.03120148]
 [-0.71818485 -0.08536656  0.51489708  0.46022177]]
[[ 3.  4.  5.]
 [-6. -4.  2.]
 [ 1.  8.  2.]
 [ 7.  8.  9.]]
